version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: "service_account"
    project_id: "myfirstproject-364809"
    private_key_id: "546cf6e74c85d41f20b3478d27414df5f64b4f74"
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgukY4uXra+OSU\nreq+yl3L+KMcYJ/ZLxjWPf7RVRqsAGA+kLsuj6F1cgr/PLIp2HL8nkGZdXuOUQzS\nbDm7aa+y8vuQVl588gyymVvugUh2yV0fmso5E5m4uKA8JZSmXNkQHQbQORRxdPmV\nHYJ2CDwxJhaDnN0C0+JGvhBZHlS7V5rqAqySK+8jX0XEVM6/L+TTDprgVdNnK7z7\nDw5mnR+kHRXkxIold23Vb3wstEupI/ckBM023XemQDDWlzH2JkGTxiYnxECjSyln\nRogpVHvAc4m0+meBgEIOOibgQi0/1Zr+IAIAQsc84xHxG8bJXoxoPd3njGWpnbz4\nggZrYHb9AgMBAAECggEAF1vK/c5y/OTkL3lxHsZBSHX7mpGuWX1/Qg+je1+/bxTk\n5+LX2UX1hKCM2ZhEGlHDMFR9myRYTxAXaXNiFosfBkZK6iirNcRltQUVt71hPyY3\nmvK/hfkDw7VNUEBz8JOY1j8psNRC1NRXu2SdA7NhsBDlf74p3pHVlktkC9edH9a5\nzFEI5AH364k2yzHhvi8DO005mhNcsgFFshKS/pD64HHFkbHUe+Y+FjX7v3uP1LIX\nZl0u1JDpZNTJ2V7GzFE8nCXSFndD0HePy6c37CpGI94jQRFGzmDv3lEXQqgFtFJv\n9Wg7lJXGFsI5AaGKknA5/gwGHEI+lu3nOUCX7AIEPwKBgQDexJJANK+cCYUrpX8l\nm0siioZ2z1rOCBDfaitOvXGutZIECj9k4Y2ucZKM6x6e/IOMkuOg5BDOfVj88+W3\nMzrOmY7ei03GmmG2pF3Rdj3IXtOr2N7vdHat1s7rKhnzLy+rvLf7phjQjCNLHQE2\nP+GyThFyDMrZuPgMW6aGxfu+hwKBgQC4tGhyybNRrSPcJ9IS+/WZrPMJmMhqb8G7\nhAH/hPBTC6J+XHb53VA/WCRuass4eTzl0UIltGn+FoANpbCunr2tgelhfK73gj4l\nvI1QFRE8e4OWcHW6lVfJlud9CDHdyI60VF0ZZnN73svZ6ncL6Gm3dme1xmZafkEi\njtvexzibWwKBgA2Ru7bdfrTqf4ohEpWf1/vKpFYoW0ehhiWVuf2Z3Irf1H0agrIK\nay7tDBg5WiwlBX5SlDsAqWVqjTkbQirem/5prCIyKhKm5LzTVkOkCC9kV1BobWv4\nlCISq5f3gI0nmqfDXxGdFHXfk2bH5YMAcScDSlzAGrsYYUOfcY1UEfmRAoGBAIJ+\ng2TF+Dj2WGWMhLEA7i4asMLQ/JemSXuP8lFyvNAPYkhgT3aM08tNHMAeF2HY1huQ\nUmmNI21uvB3oOAHHCT9yj05e5sbbb8j9g+FWYQ0YPomk/qhKJvG3+eiuR3zn21qw\nV+5AIcscR224Z080bqw9rVwRxfKdTKt7vv+QRQANAoGAOo0XbyVyx9EngrzGbnPf\nWwYanmBPvja4up8vUrdnlk+lQLIyfJl89CBFet66UKyvA0OeY/paYPJd8yiO/NTr\n8q6IC4yfWxnloWkdmoQYWUbLqDKcXsU09+RC1oTnEppUAv+gghVQ3DMNfHOZ86JJ\nZvMwpCkGVZc8HWxfAZn1Pa0=\n-----END PRIVATE KEY-----\n"
    client_email: "jason2022@myfirstproject-364809.iam.gserviceaccount.com"
    # type: service_account
    # project_id: project-id
    # private_key_id: key-id
    # private_key: "-----BEGIN PRIVATE KEY-----\nyour_private_key\n-----END_PRIVATE_KEY"
    # client_email: your_service_account_email
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/jason2022%40myfirstproject-364809.iam.gserviceaccount.com"
    # client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/secrets/key.json"
#   GOOGLE_LOCATION: US # Optional
  # MongoDB
  MONGODB_DATABASE: database
  MONGODB_HOST: host
  MONGODB_PASSWORD: password
  MONGODB_PORT: 27017
  MONGODB_COLLECTION: collection
  MONGODB_USER: user
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
